### ISSUE TITLE
Изучение HTML (Базовая разметка)

### ISSUE THREAD

**Issue by dmowski** [Madiy/FtS#12]
- [x] Базовая разметка. Понять что такое тэг и атрибут

- [x] Для чего нужен DOCTYPE
- [x] Тэг html
- [x] Тэг head
- [x] Тэг meta
- [x] Тэг title

- [x] Тэг body
- [x] Тэг a
- [x] Тэг p

Алгоритм выполнения задания
1. Создаешь ветку на основе ветки master

2. Добавляешь пустой файл (basic.html) / Делаешь коммит и в сообщении коммита коротко пишешь для чего нужны тэги и атрибуты

3. В файл basic.html добавляешь DOCTYPE / Делаешь коммит и в сообщении коммита коротко пишешь для чего нужен DOCTYPE

4. В файл basic.html добавляешь тэг html / Делаешь коммит и в сообщении коммита коротко пишешь для чего нужен html

5. В файл basic.html добавляешь тэг head/ Делаешь коммит и в сообщении коммита коротко пишешь для чего нужен head

6. В файл basic.html добавляешь тэг meta/ Делаешь коммит и в сообщении коммита коротко пишешь для чего нужен meta

и так для каждого тэга

**Comment by Madiy** [comment]
Что значит "сообщение коммита"?

**Comment by dmowski** [comment]
![image](https://cloud.githubusercontent.com/assets/17089422/21748951/91292ea6-d5a3-11e6-9c13-0a45c4184c75.png)
текст который ты пишешь, когда создаешь коммит
